### ISSUE TITLE
java error on OFF command

### ISSUE THREAD

**Issue by pietrocostanzo** [lucacalcaterra/org.openhab.binding.melcloud#13] opened 2019-08-27 14:14 UTC
hello
fisrt thanks to luca for her work... 
i have rapsberry pi whit last openHABian version installed
zulu java framework
last version 'SNAPSHOT' of melcloud addon 

serarch and binding work
bat when i send a command i have an error...

2019-08-26 16:37:28.053 [WARN ] [ternal.handler.MelCloudDeviceHandler] - Command 'OFF' to channel 'melcloud:acdevice:d34566ebb:146764:power' failed, reason Error occured during device command sending. 
org.openhab.binding.melcloud.internal.exceptions.MelCloudCommException: Error occured during device command sending
         at org.openhab.binding.melcloud.internal.api.MelCloudConnection.sendDeviceStatus(MelCloudConnection.java:159) ~[246:org.openhab.binding.melcloud:2.5.0.201908090920]
         at org.openhab.binding.melcloud.internal.handler.MelCloudAccountHandler.sendDeviceStatus(MelCloudAccountHandler.java:138) ~[246:org.openhab.binding.melcloud:2.5.0.201908090920]
         at org.openhab.binding.melcloud.internal.handler.MelCloudDeviceHandler.handleCommand(MelCloudDeviceHandler.java:205) [246:org.openhab.binding.melcloud:2.5.0.201908090920]
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
         at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
         at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [102:org.eclipse.smarthome.core:0.10.0.oh240]
         at com.sun.proxy.$Proxy160.handleCommand(Unknown Source) [246:org.openhab.binding.melcloud:2.5.0.201908090920]
         at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]
         at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
         at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
         at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.10.0.oh240]
         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
         at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $
         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[?:?]
         at com.google.gson.Gson.fromJson(Gson.java:927) ~[?:?]
         at com.google.gson.Gson.fromJson(Gson.java:892) ~[?:?]
         at com.google.gson.Gson.fromJson(Gson.java:841) ~[?:?]
         at com.google.gson.Gson.fromJson(Gson.java:813) ~[?:?]
         at org.openhab.binding.melcloud.internal.api.MelCloudConnection.sendDeviceStatus(MelCloudConnection.java:156) ~[?:?]
         ... 21 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $
         at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[?:?]
         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[?:?]
         at com.google.gson.Gson.fromJson(Gson.java:927) ~[?:?]
         at com.google.gson.Gson.fromJson(Gson.java:892) ~[?:?]
         at com.google.gson.Gson.fromJson(Gson.java:841) ~[?:?]
         at com.google.gson.Gson.fromJson(Gson.java:813) ~[?:?]
         at org.openhab.binding.melcloud.internal.api.MelCloudConnection.sendDeviceStatus(MelCloudConnection.java:156) ~[?:?]
         ... 21 more

**Comment by lucacalcaterra** [comment] 2019-08-27 14:30
@pietrocostanzo You must describe correctly the issue if you want that somone can fix the bug :-)

**Comment by pietrocostanzo** [comment] 2019-08-28 09:47
is possible? 
Gson is expecting your JSON string to begin with an object opening brace. e.g.
{
But the string you have passed to it starts with an open quotes
"

maybe default language setting?

**Comment by lucacalcaterra** [comment] 2019-08-28 09:58
Probably a wrong  parsing  of object response. But in the latests  release  there  are improvments  from other  authors  ,i'll need to check asap. 

In which  language  you  sets  the binding ? Maybe   your  structure  of objects  in melcloud (tree  levels)

**Comment by pietrocostanzo** [comment] 2019-08-28 10:14
i change my structure of objects in melcloud all in first level... becouse in tree levels binding not found...

i modify language setting from italian to english in openhab and in melcloud app 
remove and add thing
bat....



2019-08-28 12:06:23.974 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.melcloud.internal.handler.MelCloudDeviceHandler@57567tf': java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[234:com.google.gson:2.8.5]

	at com.google.gson.Gson.fromJson(Gson.java:927) ~[234:com.google.gson:2.8.5]

	at com.google.gson.Gson.fromJson(Gson.java:892) ~[234:com.google.gson:2.8.5]

	at com.google.gson.Gson.fromJson(Gson.java:841) ~[234:com.google.gson:2.8.5]

	at com.google.gson.Gson.fromJson(Gson.java:813) ~[234:com.google.gson:2.8.5]

	at org.openhab.binding.melcloud.internal.api.MelCloudConnection.sendCommand(MelCloudConnection.java:134) ~[?:?]

	at org.openhab.binding.melcloud.internal.handler.MelCloudAccountHandler.sendCommand(MelCloudAccountHandler.java:135) ~[?:?]

	at org.openhab.binding.melcloud.internal.handler.MelCloudDeviceHandler.handleCommand(MelCloudDeviceHandler.java:191) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]

	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [102:org.eclipse.smarthome.core:0.10.0.oh240]

	at com.sun.proxy.$Proxy144.handleCommand(Unknown Source) [250:org.openhab.binding.melcloud:2.5.0.201906261023]

	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]

	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.10.0.oh240]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $

	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[?:?]

	... 26 more

**Comment by thewiep** [comment] 2019-08-28 10:51
Hi @pietrocostanzo,

to summarize:
- you are using v 2.3 of the binding
- devices in tree structure are not discovered
- you cannot send a command

strange because I made some changes so all devices on all levels are discovered and it works fine here.
I've also been using this version since release with no issues.
Perhaps I missed something :).
Can you increase logging for the binding through Karaf?
`log:set DEBUG org.openhab.binding.melcloud`
This will show the JSON in the log.

Thanks.

**Comment by pietrocostanzo** [comment] 2019-08-28 12:04
set log debug... and...

2019-08-28 14:00:19.122 [vent.ItemStateChangedEvent] - Giorno_Power changed from ON to OFF

==> /var/log/openhab2/openhab.log <==

2019-08-28 14:00:19.354 [DEBUG] [loud.internal.api.MelCloudConnection] - Command response: 

<!DOCTYPE html>

<html>

<head>

    <meta name="viewport" content="width=device-width" />

    <title>Error</title>

    <style type="text/css">

        BODY, P {

            font-family: sans-serif;

        }

    </style>

</head>

<body>

    <div style="text-align: center">

        <a href="http://www.melcloud.com"><img style="max-width: 100%;" src="/css/assets/logo-wide.png" alt="MELCloud" /></a>

    </div>

    <h1>Unexpected Error</h1>

    

        <p>An unexpected error has occurred. 

        <a href="http://www.melcloud.com">Please return to the home page.</a></p>

    <p>Diagnostic information: Unexpected Internal Error 8764226706</p>

</body>

</html>

2019-08-28 14:00:19.359 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.melcloud.internal.handler.MelCloudDeviceHandler@1******': java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $
,,,,

**Comment by pietrocostanzo** [comment] 2019-08-28 12:56
2019-08-28 14:46:09.548 [DEBUG] [ernal.handler.MelCloudAccountHandler] - Check MELCloud connection

2019-08-28 14:46:09.556 [DEBUG] [ernal.handler.MelCloudAccountHandler] - Connection to MELCloud open

==> /var/log/openhab2/events.log <==

2019-08-28 14:46:31.481 [ome.event.ItemCommandEvent] - Item 'ACDeviceGiorno_Power' received command ON

2019-08-28 14:46:31.496 [nt.ItemStatePredictedEvent] - ACDeviceGiorno_Power predicted to become ON

2019-08-28 14:46:31.500 [vent.ItemStateChangedEvent] - ACDeviceGiorno_Power changed from OFF to ON

==> /var/log/openhab2/openhab.log <==

2019-08-28 14:46:31.494 [DEBUG] [ternal.handler.MelCloudDeviceHandler] - Received command 'ON' to channel melcloud:acdevice:************:power

2019-08-28 14:46:31.507 [DEBUG] [loud.internal.api.MelCloudConnection] - Sending device status: {"EffectiveFlags":1,"OperationMode":0,"DeviceID":********,"Power":true,"HasPendingCommand":true}

2019-08-28 14:46:31.986 [DEBUG] [loud.internal.api.MelCloudConnection] - Device status sending response: 

<!DOCTYPE html>

<html>

<head>

    <meta name="viewport" content="width=device-width" />

    <title>Error</title>

    <style type="text/css">

        BODY, P {

            font-family: sans-serif;

        }

    </style>

</head>

<body>

    <div style="text-align: center">

        <a href="http://www.melcloud.com"><img style="max-width: 100%;" src="/css/assets/logo-wide.png" alt="MELCloud" /></a>

    </div>

    <h1>Unexpected Error</h1>

    

        <p>An unexpected error has occurred. 

        <a href="http://www.melcloud.com">Please return to the home page.</a></p>

    <p>Diagnostic information: Unexpected Internal Error 8769321885</p>

</body>

</html>

2019-08-28 14:46:31.988 [DEBUG] [ernal.handler.MelCloudAccountHandler] - Sending failed, retry once with relogin

2019-08-28 14:46:31.989 [DEBUG] [ernal.handler.MelCloudAccountHandler] - Initializing connection to MELCloud
....

2019-08-28 14:46:32.591 [WARN ] [ternal.handler.MelCloudDeviceHandler] - Command 'ON' to channel 'melcloud:acdevice:******:******:power' failed, reason Error occured during device command sending. 

org.openhab.binding.melcloud.internal.exceptions.MelCloudCommException: Error occured during device command sending

.....

2019-08-28 14:47:09.901 [DEBUG] [loud.internal.api.MelCloudConnection] - Found 2 devices

2019-08-28 14:47:09.905 [DEBUG] [ternal.handler.MelCloudDeviceHandler] - bridgeStatusChanged ONLINE for thing melcloud:acdevice:*****

2019-08-28 14:47:09.905 [DEBUG] [ternal.handler.MelCloudDeviceHandler] - bridgeStatusChanged ONLINE for thing melcloud:acdevice:********

2019-08-28 14:47:09.907 [DEBUG] [ternal.handler.MelCloudDeviceHandler] - initializeBridge ONLINE for thing melcloud:acdevice:********

2019-08-28 14:47:09.907 [DEBUG] [ternal.handler.MelCloudDeviceHandler] - initializeBridge ONLINE for thing melcloud:acdevice:************

==> /var/log/openhab2/events.log <==

2019-08-28 14:47:09.907 [hingStatusInfoChangedEvent] - 'melcloud:melcloudaccount:******' changed from OFFLINE to ONLINE

2019-08-28 14:47:09.915 [hingStatusInfoChangedEvent] - 'melcloud:acdevice:****:********' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE

2019-08-28 14:47:09.920 [hingStatusInfoChangedEvent] - 'melcloud:acdevice:****:*******' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE

2019-08-28 14:49:09.909 [DEBUG] [ernal.handler.MelCloudAccountHandler] - Check MELCloud connection

2019-08-28 14:49:09.913 [DEBUG] [ernal.handler.MelCloudAccountHandler] - Connection to MELCloud open

**Comment by thewiep** [comment] 2019-08-28 16:30
The binding is sending correctly formatted data ("Sending device status") but it seems MELCloud is expecting something different ("Device status sending response").

What type of devices do you have?
I assume that controlling it from MELCloud directly works as expected?

**Comment by pietrocostanzo** [comment] 2019-08-28 17:15
I have two hydrobox ersd-vm2c whit mac-557if-e wifi interfacce 

Yes with melcloud app or web page works correctly

**Comment by thewiep** [comment] 2019-08-28 17:28
I think they expect different information in the request.
I have AC devices so can't check the data that's being transferred for your type of device.

Could you:
- open up MELCloud in Chrome and login
- press F12
- select Network on top
- enable power for your device in MELCloud
- click the "SetAta" item that shows up in the list
- check Headers - Request Payload and click "view source"
- copy this JSON here (you can modify data to remove personal info but please keep the same type)

**Comment by pietrocostanzo** [comment] 2019-08-28 17:34
{EffectiveFlags: 1, LocalIPAddress: null, SetTemperatureZone1: 30, SetTemperatureZone2: 20,…}
DeviceID: *******
DeviceType: 1
EcoHotWater: true
EffectiveFlags: 1
ErrorCode: 8000
ErrorMessage: null
ForcedHotWaterMode: false
HCControlType: 2
HasPendingCommand: true
HolidayMode: false
IdleZone1: false
IdleZone2: true
LastCommunication: "2019-08-28T17:30:22.967"
LocalIPAddress: null
NextCommunication: "2019-08-28T17:31:22.967"
Offline: false
OperationMode: 3
OperationModeZone1: 3
OperationModeZone2: 4
OutdoorTemperature: 30
Power: false
ProhibitHotWater: false
ProhibitZone1: false
ProhibitZone2: false
RoomTemperatureZone1: 28.5
RoomTemperatureZone2: -39
Scene: null
SceneOwner: null
SetCoolFlowTemperatureZone1: 12
SetCoolFlowTemperatureZone2: 20
SetHeatFlowTemperatureZone1: 20
SetHeatFlowTemperatureZone2: 20
SetTankWaterTemperature: 42
SetTemperatureZone1: 30
SetTemperatureZone2: 20
TankWaterTemperature: 40
TemperatureIncrementOverride: 2
UnitStatus: 0
WeatherObservations: [{Date: "2019-08-28T21:00:00", Sunrise: "2019-08-28T06:19:00", Sunset: "2019-08-28T19:33:00",…},…]
Zone1Name: null
Zone2Name: null


thank you very much

**Comment by thewiep** [comment] 2019-08-28 20:35
Thanks for the info.
It doesn't seem to be a full reply but the parts used for the AC devices and your device seem the same.
Perhaps your device needs additional parts.
Your device is another type (DeviceType=1 and for AC it's 0) and it has different properties.
This means that in order to support it the device type and proper channels would need to be added.
To look into this I would need to do some tests to get all properties etc.
I can create a config in Postman that you can use to get the base info and test some requests and we can take it from there.

Apart from this I'll also look into prevening your type of devices being mapped to AC device.
@lucacalcaterra, can you check if your DeviceType is also 0?

**Comment by pietrocostanzo** [comment] 2019-08-28 20:55
If u want i creare new guest user on melcloud and send u ssh access on raspian

**Comment by thewiep** [comment] 2019-08-28 21:30
A guest account for MELCloud would indeed be handy if you don't mind.
My e-mail address is my GitHub username @ gmail.com.
I would need to test a command so if you could send me an e-mail we can discuss when I perform some tests so you know in advance when something will happen :)
I'll then add relevant info to the this issue.

**Comment by lucacalcaterra** [comment] 2019-08-29 12:38
> Thanks for the info.
> It doesn't seem to be a full reply but the parts used for the AC devices and your device seem the same.
> Perhaps your device needs additional parts.
> Your device is another type (DeviceType=1 and for AC it's 0) and it has different properties.
> This means that in order to support it the device type and proper channels would need to be added.
> To look into this I would need to do some tests to get all properties etc.
> I can create a config in Postman that you can use to get the base info and test some requests and we can take it from there.
> 
> Apart from this I'll also look into prevening your type of devices being mapped to AC device.
> @lucacalcaterra, can you check if your DeviceType is also 0?

Yes... My  DeviceType is 0.

@pietrocostanzo has a different model... must be managed on binding ?

**Comment by thewiep** [comment] 2019-08-29 14:13
Thanks for confirming.
The device will indeed need a separate thing in the binding.
In the discovery service the acdevice gets linked automatically, we need to check the type there and link the proper thing.
Pietro provided me guest access so I'll try to get the required info from MELCloud.
If you want I can take a look at implementing this.

**Comment by thewiep** [comment] 2019-08-30 06:35
@pietrocostanzo, I can reproduce the issue and would now need to toggle some command to get the data we need.
Can I toggle power a few times between 12.30 and 13.00?
I'll make sure it ends up in the same state as before I started.

**Comment by pietrocostanzo** [comment] 2019-08-30 08:00
Yes... 
Go!!!
if you need maybe at 12.30 I will be to home 😉
Thank you

**Comment by thewiep** [comment] 2019-08-30 11:14
This device is using a different endpoint.
For AC Device it's SetAta and for this device it's SetAtw.
The command needed to change power is the same.
You might have noticed the power toggeling, this was done with a request outside of MELCloud.

I will make note of what needs to be done and check to start implementation.

I don't what the device is actually used for and which settings are needed.
Can you explain which parts would be useful as a channel?
Power seem like a good one to start with :)

**Comment by pietrocostanzo** [comment] 2019-08-30 12:24
my project, my idea
I have photovoltaic electricity production for 2.4 kw
when there is electricity production, I would like to start by heating water and the ambient temperature 

then

on off
set water temperature
set room temperature
electrical absorption
start and stop

obviously all the routines then I'll do them on openhab

Thank you  very much

**Comment by pietrocostanzo** [comment] 2019-09-02 16:59
then?
do i have hopes?😉

**Comment by thewiep** [comment] 2019-09-02 19:05
I was away for the biggest part of the weekend but started implementation yesterday evening.
The base is done and I currently have a channel for Power, I tested this yesterday and it works fine.
I hope to finish this part today or tomorrow latest and provide you with a test version.

I need to get the proper EffectiveFlags values for the other channels and implement those next.
I will test these values by changing a value and set it back to the original value afterwards (for example set temperature a degree lower and then back).

I'll probably provide another version to test when that's done and if you tested it and all is ok I'll create a PR that can be merged here.

**Comment by thewiep** [comment] 2019-09-02 20:06
@pietrocostanzo, here's a version you can test:
[org.openhab.binding.melcloud-2.5.0-SNAPSHOT_20190902_heatpump.zip](https://github.com/lucacalcaterra/org.openhab.binding.melcloud/files/3567024/org.openhab.binding.melcloud-2.5.0-SNAPSHOT_20190902_heatpump.zip)

It currently has channels for:
- Power
- Has Pending Command
- Last Communication
- Next Communication

with Power you can already test activating and deactivating if you want.
I'll try to add the rest later this week :)

**Comment by pietrocostanzo** [comment] 2019-09-03 09:20
I confirm
try ok
Thank you

**Comment by thewiep** [comment] 2019-09-04 15:56
@pietrocostanzo, thanks for testing!
I added channels:
- Force Hot Water Mode
- Set Temperature Zone 1
- Room Temperature Zone 1 (read only)
- Is Offline (read only)

I tested and they work, could you test it from your end?
[org.openhab.binding.melcloud-2.5.0-SNAPSHOT_20190904_heatpump.zip](https://github.com/lucacalcaterra/org.openhab.binding.melcloud/files/3575377/org.openhab.binding.melcloud-2.5.0-SNAPSHOT_20190904_heatpump.zip)

I don't see any option in MELCloud to set water temperature or anything related to electrical absorption so I don't think this option is available.

I didn't implement Zone 2 as I can't test because your device doesn't seem to have a Zone 2 so I can't confirm the EffectiveFlags value

**Comment by pietrocostanzo** [comment] 2019-09-05 18:15
I tried everything perfectly
what could you add?
water temperature reading?
reading of energy consumption?
thnak you very much for all

ps i have only zone 1 ;)

**Comment by thewiep** [comment] 2019-09-06 17:38
I don't see any information about energy consumption in feedback from MELCloud.
Is this info visible for you in the MELCloud app?

I did add a read-only channel for TankWaterTemperature, you can test it here
[org.openhab.binding.melcloud-2.5.0-SNAPSHOT_20190906_heatpump.zip](https://github.com/lucacalcaterra/org.openhab.binding.melcloud/files/3585007/org.openhab.binding.melcloud-2.5.0-SNAPSHOT_20190906_heatpump.zip)

I think I'll try to finish up the implementation and prepare a PR after @lucacalcaterra has the binding merged into the official repo.

**Comment by lucacalcaterra** [comment] 2019-09-06 17:56
@thewiep you can pr on the my forked openhab2-addons (as wrote yesterday in README ).

I also open a PR to the openhab2-addons master repo 

Here is my fork: 
https://github.com/lucacalcaterra/openhab2-addons

Here is the PR to openhab official addons  repo:
https://github.com/openhab/openhab2-addons/pull/6032


ps when commit you must sign-off them

**Comment by pietrocostanzo** [comment] 2019-09-07 07:47
Il Ven 6 Set 2019, 19:56 Luca Calcaterra <notifications@github.com> ha
scritto:

**Comment by thewiep** [comment] 2019-10-13 11:06
@pietrocostanzo would it be possible to enable guest access again for a short time?
I'm updating a previous PR and just want to verify everything is ok.
Thanks!

**Comment by pietrocostanzo** [comment] 2019-10-13 13:50
Yes
Pls send me email adr

Il Dom 13 Ott 2019, 13:06 Wietse van Buitenen <notifications@github.com> ha
scritto:

**Comment by thewiep** [comment] 2019-10-13 14:36
great, thanks.
My e-mail address is thewiep@gmail.com

**Comment by thewiep** [comment] 2019-10-15 18:36
@pietrocostanzo perhaps you didn't get a notification because because I didn't mention you so I'll try it again :)
My e-mail address is thewiep@gmail.com

**Comment by pietrocostanzo** [comment] 2019-10-16 15:54
Ready
Sorry distrsction time 😉

Il Dom 13 Ott 2019, 16:36 Wietse van Buitenen <notifications@github.com> ha
scritto:

**Comment by thewiep** [comment] 2019-10-16 20:35
@pietrocostanzo no worries :)
Thanks a lot for allowing guest access!
I tested the parts I needed to test and it's looking good.
You can remove my access again.

**Comment by Vincentpigree** [comment] 2019-11-01 17:51
hello to all and thank you for the work done
 I managed to install the binding melcloud!
I write in the file things.
I manage to install the account

Bridge melcloud:melcloudaccount:myaccount "maison" [ username="******", password="*****", language="7" ] {

but how does the thing create?

 Thing ?????  [ deviceID=123456, pollingInterval=60 ]

thanks for the information !!

**Comment by lucacalcaterra** [comment] 2019-11-01 19:07
> hello to all and thank you for the work done
> I managed to install the binding melcloud!
> I write in the file things.
> I manage to install the account
> 
> Bridge melcloud:melcloudaccount:myaccount "maison" [ username="*_****", password="****_", language="7" ] {
> 
> but how does the thing create?
> 
> Thing ????? [ deviceID=123456, pollingInterval=60 ]
> 
> thanks for the information !!

No need to do... you can  create things from ui  with autodiscovery feature.

**Comment by Vincentpigree** [comment] 2019-11-01 19:35
yes I know but I prefer all write I find it easier because I understand better after to create my link with the sitemap

**Comment by thewiep** [comment] 2019-11-01 19:40
I also prefer to work with files :) 
The README.md contains samples for each device.

**Comment by Vincentpigree** [comment] 2019-11-01 20:00
yes i have seen the README md file but i find that its
    Thing acdevice livingroom "Livingroom A.C. device" [ deviceID=123456, pollingInterval=60 ]

except that I'm on a Heatpump 
and when I get in

Thing Heatpump Device  "piece central" [ deviceID=53347,buildingID=18760, pollingInterval=60 ]

no error my nothing is added

**Comment by thewiep** [comment] 2019-11-01 20:10
sorry, I didn't mean to imply you haven't read the docs.
Heatpump should be lowercase.
The readme from the PR which includes the Heatpump should contain correct examples.
Can you check:
https://github.com/thewiep/openhab2-addons/blob/4b93062cf6dc6be833b291981378c38da58dc7d9/bundles/org.openhab.binding.melcloud/README.md

**Comment by Vincentpigree** [comment] 2019-11-01 20:30
ok i'm looking at her tomorrow thanks for this valuable information !!!!!

**Comment by Vincentpigree** [comment] 2019-11-02 07:53
I manage to have my account with
Bridge melcloud:melcloudaccount:myaccount "maison" [ username="*****", password="******", language="7" ] {

but I can come back my things nothing has made it does not appear
Thing heatpump attic "Attic Heatpump device" [ deviceID=53347,buildingID=18760, pollingInterval=60 ] 
}

where is my mistake ??

and how to start debug mode???

**Closed as completed** 2020-10-18 08:57 UTC
